default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['postgresql_username'] %>
  pssword: <%= ENV['postgresql_password'] %>
  pool: 5

development:
  <<: *default
  database: FuelTheLife_development

test:
  <<: *default
  database: FuelTheLife_test

production:
  <<: *default
  database: FuelTheLife_production
  username: FuelTheLife
  password: <%= ENV['FUELTHELIFE_DATABASE_PASSWORD'] %>
